version: 2

models:
  - name: silver_clean_biosignals
    columns:
      - name: participation_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_clean_participation')
              field: participation_id
        
      - name: timestamp
        tests:
          - not_null

  - name: silver_clean_blendshapes
    columns:
      - name: participation_id
        tests:
          - not_null
        
      - name: timestamp
        tests:
          - not_null

  - name: silver_clean_emotions
    columns:
      - name: participation_id
        tests:
          - not_null
      
      - name: dominant
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['HAPPY', 'SAD', 'ANGRY', 'SURPRISE', 'DISGUST', 'NEUTRAL']

  - name: silver_clean_participant
    columns:
      - name: participant_id
        tests:
          - not_null
          - unique

  - name: silver_clean_session
    columns:
      - name: session_id
        tests:
          - not_null
          - unique

  - name: silver_clean_participation
    columns:
      - name: participation_id
        tests:
          - not_null
          - unique

      - name: participant_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_clean_participant')
              field: participant_id

      - name: session_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_clean_session')
              field: session_id